import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get/state_manager.dart';
import 'package:my_app/controllers/home_controller.dart';
import 'package:get/route_manager.dart';
import 'package:my_app/pages/task_page.dart';

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<HomeController>(
        init: HomeController(),
        builder: (_) {
          return Scaffold(
            appBar: AppBar(
              centerTitle: true,
              title: Text(
                'Intl Flutter Application',
              ), // Using the translation generated by the AppLocalization class imported on top of this script
            ),
            body: SafeArea(
              child: Container(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      margin: EdgeInsets.only(bottom: 20.0, top: 20.0),
                      child: Center(
                          child: Text(
                        'My tasks',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                            fontSize: 20.0, fontWeight: FontWeight.bold),
                      )),
                    ),
                    Expanded(
                      child: ListView(),
                    ),
                  ],
                ),
              ),
            ),
            floatingActionButton: FloatingActionButton(
              onPressed: () {
                // _.increment();
                Get.to(() => TaskPage(), transition: Transition.fadeIn);
              },
              child: Icon(Icons.add),
            ),
          );
        });
  }
}

              // child: GetBuilder<HomeController>(
              //   id: 'text',
              //   builder: (_) => Text(_.counter.toString()),
              // ),
